#!/usr/bin/env bash

tty="/dev/ttyUSB0"   # change this
count=0
while IFS= read -r line <"$tty"; do
    printf '%s %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$line"
    if [[ "${line,,}" == *fail* ]]; then
        break
    fi
done
  
for i in {1..10}; do
    IFS= read -r line < "$tty"
    printf '%s %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$line"
done   
